### ISSUE TITLE
Connection is successful, can not perform onReceiveDot

### ISSUE THREAD

**Issue by wushangjun** [NeoSmartpen/AndroidSample#1]
Connection is successful, can not perform onReceiveDot, what is the reason? Model: NWP-F110

**Comment by mrlove1** [comment]
Hi wushangjun

1. Do you wrote by our pen at NCoded Paper?
2. Do you use SDK library API "reqAddUsingNote" or "reqAddUsingNoteAll"?
If you develop not  business app but sample app, i recommend to use  "reqAddUsingNoteAll".
Please see listener "onReceiveMessage" of PenClientCtrl class.

Best Regard,
Moosaeng.

**Comment by wushangjun** [comment]
Thank you for using "reqAddUsingNoteAll"
